# Generated by Django 4.0.5 on 2022-06-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_supervisor_employee_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
