# Generated by Django 4.0.4 on 2022-06-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(choices=[('ENG', 'English'), ('GER', 'German'), ('FRN', 'French'), ('POR', 'Portugese')], default='ENG', max_length=20),
        ),
    ]
