# Generated by Django 4.0.4 on 2022-06-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='picture',
            new_name='profile_picture',
        ),
    ]
