# Generated by Django 4.0.4 on 2022-06-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_language_user_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('GER', 'German'), ('FRN', 'French'), ('POR', 'Portugese')], default='', max_length=20, verbose_name='Languages'),
        ),
    ]
