# Generated by Django 4.0.4 on 2022-06-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='languages',
            new_name='language',
        ),
    ]
