# Generated by Django 4.0.4 on 2022-06-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
