# Generated by Django 4.0.5 on 2022-06-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Portugese', 'Portugese')], default='', max_length=20, verbose_name='Languages'),
        ),
    ]
