# Generated by Django 4.0.5 on 2022-06-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
