# Generated by Django 4.0.5 on 2022-06-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_user_country_remove_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
