# Generated by Django 4.0.5 on 2022-06-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_kpiconfig_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiconfig',
            name='rating',
            field=models.CharField(blank=True, choices=[('1. Exceeded.', '1. Exceeded.'), ('2. Achieved all aspects.', '2. Achieved all aspects.'), ('3. Achieved the essnential requirements.', '3. Achieved the essnential requirements.'), ('4. Did not achieve.', '4. Did not achieve.')], default='', max_length=255, verbose_name='rating'),
        ),
    ]
