# Generated by Django 4.0.5 on 2022-06-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_kpiconfig_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='sbu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_sbu', to='base.sbu'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kpiconfig',
            name='rating',
            field=models.CharField(blank=True, choices=[('1. Exceeded.', '1. Exceeded.'), ('2. Achieved all aspects.', '2. Achieved all aspects.'), ('3. Achieved the essnential requirements.', '3. Achieved the essnential requirements.'), ('4. Did not achieve.', '4. Did not achieve.')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='subsbu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_sub_sbu', to='base.subsbu'),
        ),
    ]
