# Generated by Django 4.0.5 on 2022-06-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_reviewrating_alter_kpiconfig_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='subsbu',
            new_name='sub_sbu',
        ),
    ]
