# Generated by Django 4.0.5 on 2022-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_user_role_user_group_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
